### PR TITLE
Added a function to read movies in from a text file

### PR DESCRIPTION
**Pull request by stonehenj**

### CODE REVIEW

**Comment by zaneobrien** [comment]
Thanks, works great!

**Comment by zaneobrien** [comment]
Can you explain why you added these to the year and titles. 

year = atoi(syear.c_str());

I dont understand why this is needed

**Comment by stonehenj** [comment]
atoi converts a string to an int. I'm pretty sure you had a similar function called stoi. But I'm pretty sure stoi is only a function for c++ 11, which since mine didn't compile with stoi I guess I'm using an earlier version of c++. So instead of figuring out how to update my version of c++, I used atoi which works on all versions. Also atoi takes in a char so that's what .c_str() is for, it converts a string to a char.

**Comment by stonehenj** [comment]
You're obviously welcome to change it back to stoi

**Comment by zaneobrien** [comment]
Okay that makes sense. yeah stoi is only for c++ 11.

**Pull request merged**
